### ISSUE TITLE
[Bug Report] 界面操作流程异常导致功能失效 - 期望与实际行为不符

### ISSUE THREAD

**Issue by Yangxiaoba** [fit2cloud-edu/MeterSphere#13]
概述: 在使用Metersphere的过程中，发现了一处可能影响用户体验的功能性问题。当用户按照特定的操作流程进行操作时，出现了不符合预期的结果。

重现步骤:

 登录Metersphere平台，并选择某个已创建的测试项目。
 在该项目下创建新的测试计划，并成功添加了若干测试用例到该计划中。
 启动测试计划执行，并观察执行过程及结果展示。
Bug行为: 在执行完步骤ccc后，测试计划虽然启动成功，但测试结果并未正确更新到界面中。具体表现为：测试用例的实际执行结果（无论通过与否）未及时刷新在测试报告区域，而且后台日志中也未显示出正确的执行反馈信息。

期望行为: 按照设计逻辑，完成步骤ccc后，Metersphere平台应当实时更新测试计划的执行进度并在测试报告中显示出每个测试用例的执行结果（包括通过、失败或跳过等状态），同时后台日志应该详细记录每一步的执行情况，便于用户查看和分析。

**Comment by xueqidove** [comment]
请反馈与高校合作计划相关的问题
