### ISSUE TITLE
能提供 Halo 的需求文档吗

### ISSUE THREAD

**Issue by xueqidove** [fit2cloud-edu/MeterSphere#2]
希望能提供一份 Halo 的需求文档。

**Comment by lixuejun725** [comment]
您好，Halo在线环境已经提供在线文档，地址：https://docs.halo.run       
也可通过在线前端环境里面查看，如下图，请查收
![image](https://user-images.githubusercontent.com/38548829/233910051-8d422196-ba06-4073-b6ff-bd1be06abe1d.png)
