### ISSUE TITLE
增加在线的API接口使用

### ISSUE THREAD

**Issue by GTA-lxs** [fit2cloud-edu/MeterSphere#25]
1.增加API在线接口，方便使用，在线测试模块功能
2.创建一个API沙箱环境，供开发者测试和验证API功能。
3.提供关于如何使用API的培训和教育材料，帮助用户更好地理解和利用API功能。
4.记录API调用的详细日志，方便排查问题和进行性能分析。
例如hugging face的在线API：
<img width="416" alt="image" src="https://github.com/fit2cloud-edu/MeterSphere/assets/154776457/ee16e438-b0aa-499f-b52e-e2241b690814">

**Comment by xueqidove** [comment]
《软件测试实训手册》重点是教学生如何基于MeterSphere专业测试云完成相关实训，其中包含API的调试，后续我们会在MeterSphere专业测试云平台完成API调试功能，感谢您的反馈！
