### ISSUE TITLE
建议把接口定义转用例，以及参数的提取内容放到“接口自动化”实验中

### ISSUE THREAD

**Issue by xueqidove** [fit2cloud-edu/MeterSphere#7]
建议把接口定义转用例，以及参数的提取内容放到“接口自动化”实验中。
因为参数化及调用，只在接口自动化中能看到结果。

**Comment by lixuejun725** [comment]
感谢反馈，这个因为存在一个连贯性，因为接口转用例的前提是接口已经创建，如果放在接口自动化这里，事先如果没有创建接口的情况下，这里还是需要进行创建接口的，所以我们把接口转用例放到了接口测试实验那里。如果此处没有用例使用可以转到第五章完成实验之后再进行实验六
