### ISSUE TITLE
实验七获取用例列表改为获取文章列表

### ISSUE THREAD

**Issue by xueqidove** [fit2cloud-edu/MeterSphere#8]
表格7-2-1接口用例以及7-2-2中的获取用例列表均不对，应该是获取文章列表

![image](https://github.com/fit2cloud-edu/MeterSphere/assets/60059766/8d7c9493-da84-4ae1-9957-515b70641d5a)

**Comment by lixuejun725** [comment]
感谢反馈，后续1.1.1版本将会更新
